### PR TITLE
Update to cats-effect-3

### LINKED ISSUE #185: Cats Effect 3 support
It would be great to have a version of this library supporting CE3

### PR DESCRIPTION
**Pull request by dininski**
Closes #185

### CODE REVIEW

**Review by LukaJCB — APPROVED** [review]
Thanks so much!

**Comment by dininski** [comment]
This PR should be ready to merge. However because https://github.com/compstak/kafka-connect-http4s has not yet released a ce3-compatible version yet, the PR uses a GH project to pull in a CE3 compatible version of kafka-connect-http4s.

**Comment by LukaJCB** [comment]
Http4s just released a CE3 compatible 0.23.0 final, so let's get `kafka-connect-http4s` onto that and then get this merged! Tysm!

**Comment by dininski** [comment]
> Http4s just released a CE3 compatible 0.23.0 final, so let's get `kafka-connect-http4s` onto that and then get this merged! Tysm!

Update the related PR with 0.23.1, which is latest stable. Mind taking a look? Keep it mind that it also needs to be released in order to update this PR 🙂

**Comment by dininski** [comment]
@LukaJCB Updated the PR with the latest released version of kafka connect http4s (0.6.0), so it should be fine to merge and release now.

**Comment by LukaJCB** [comment]
Awesome thanks!

**Pull request merged**
